### ISSUE TITLE
Windows Ruby CA certificate error - potential fix?

### ISSUE THREAD

**Issue by starchx** [ampedandwired/bora#29]
This is not a Bora issue, but I couldn't find a workaround for Bora to work.
```
$ bora show_current example-qa
D:/dev/tools/ruby-2.3.1-x64-mingw32/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Seahorse::Client::NetworkingError)
        from D:/dev/tools/ruby-2.3.1-x64-mingw32/lib/ruby/2.3.0/net/http.rb:933:in `connect'
        from D:/dev/tools/ruby-2.3.1-x64-mingw32/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from D:/dev/tools/ruby-2.3.1-x64-mingw32/lib/ruby/2.3.0/net/http.rb:858:in `start'
        from D:/dev/tools/ruby-2.3.1-x64-mingw32/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
```
I have been Googled on this error seems to be related to Ruby on Windows, that doesn't come with ca-bundle anymore. A work around is to add 'Aws.use_bundled_cert! if Gem.win_platform?' somewhere. Any idea where I can put this for Bora to work on Windows?

**Comment by starchx** [comment]
Update RubyInstaller for Windows to 2.4.1 fixed this issue.
